'use strict';
const {shops,factories,routes}=DATA;
const $=id=>document.getElementById(id);
const ESC=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ICON={pin:'<path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1114 0Z"/><circle cx="12" cy="10" r="2.5"/>',bookmark:'<path d="M6 3h12v18l-6-4-6 4Z"/>',route:'<circle cx="5" cy="5" r="2"/><circle cx="19" cy="19" r="2"/><path d="M7 5h8a4 4 0 010 8H9a4 4 0 000 8h8"/>',factory:'<path d="M3 21V10l6 3V8l6 4V3h4l2 18Z"/><path d="M6 17h2m3 0h2m3 0h2"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 6v6l4 2"/>',copy:'<rect x="8" y="7" width="12" height="14" rx="2"/><path d="M16 7V3H4v14h4"/>',expand:'<path d="M9 3H3v6m12-6h6v6M3 15v6h6m12-6v6h-6"/>',list:'<path d="M8 6h13M8 12h13M8 18h13M3 6h1m-1 6h1m-1 6h1"/>',map:'<path d="m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2Zm6-2v16m6-14v16"/>',check:'<path d="m4 12 5 5L20 6"/>',taxi:'<path d="M4 10h16l-2-6H6Zm0 0-1 3v6h18v-6l-1-3M6 19v3m12-3v3M6 14h2m8 0h2M9 4V2h6v2"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>'};
const icon=name=>`<svg class="ico" viewBox="0 0 24 24" aria-hidden="true">${ICON[name]||ICON.pin}</svg>`;
function icons(root=document){root.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));}icons();
const CAT={benchmade:{name:'Shoemakers & select shops',short:'Craft & classics',color:'#743c40'},heritage:{name:'Heritage & boots',short:'Heritage',color:'#426458'},local:{name:'Sneakers & local labels',short:'Sneakers',color:'#566f83'},care:{name:'Care & repair',short:'Care',color:'#9b763f'}};
const all=[...shops,...factories],byId=Object.fromEntries(all.map(s=>[s.id,s]));
let saved=[];try{const old=JSON.parse(localStorage.getItem('sis-shanghai-circuit-v1')||'[]');if(Array.isArray(old))saved=[...new Set(old.filter(id=>byId[id]))];}catch{}
let state={view:'shops',layer:'today',category:'all',query:'',area:'all',era:'all',selected:null,route:null,list:false};
let storageOK=true;
function persist(){try{localStorage.setItem('sis-shanghai-circuit-v1',JSON.stringify(saved));}catch{storageOK=false;}document.querySelectorAll('.saved-count').forEach(e=>e.textContent=saved.length);}
persist();
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const map=L.map('map',{zoomControl:false,minZoom:11,maxZoom:16,zoomSnap:.25,zoomDelta:.75,scrollWheelZoom:true,attributionControl:true,maxBounds:BASEMAP.bounds,maxBoundsViscosity:.8}).setView([31.225,121.458],13);
map.attributionControl.setPrefix(false);map.attributionControl.addAttribution('© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> · <a href="https://openfreemap.org" target="_blank" rel="noopener">OpenFreeMap</a> · © <a href="https://openmaptiles.org" target="_blank" rel="noopener">OpenMapTiles</a>');
L.control.zoom({position:'topright'}).addTo(map);L.control.scale({imperial:false,maxWidth:90}).addTo(map);
const mapSVG=new DOMParser().parseFromString(BASEMAP.svg,'image/svg+xml').documentElement;
L.svgOverlay(mapSVG,BASEMAP.bounds,{interactive:false}).addTo(map);
map.createPane('labels');map.getPane('labels').style.zIndex=410;map.getPane('labels').style.pointerEvents='none';
const labels=L.layerGroup().addTo(map);const placeLabels=[
[31.238,121.440,'Jing’an','静安','district'],[31.208,121.452,'Xuhui','徐汇','district'],[31.234,121.481,'Huangpu','黄浦','district'],[31.236,121.518,'Pudong','浦东','district'],[31.218,121.410,'Changning','长宁','district'],[31.250,121.404,'Putuo','普陀','district'],[31.267,121.489,'Hongkou','虹口','district'],[31.266,121.546,'Yangpu','杨浦','district'],[31.097,121.393,'Minhang','闵行','district'],[31.225,121.495,'Huangpu River','','river'],[31.239,121.459,'Suzhou Creek','','river'],[31.230,121.470,'People’s Square','','landmark'],[31.2254,121.4407,'Jing’an Temple','','landmark'],[31.197,121.438,'Xujiahui','','landmark'],[31.225,121.483,'Yu Garden','','landmark'],[31.242,121.487,'The Bund','','landmark']];
placeLabels.forEach(([lat,lon,en,zh,kind])=>L.marker([lat,lon],{pane:'labels',interactive:false,keyboard:false,icon:L.divIcon({className:'place-label',html:`<span class="${kind}">${en}</span>${zh?`<span class="chinese">${zh}</span>`:''}`,iconSize:[150,35],iconAnchor:[75,15]})}).addTo(labels));
const streetLabels=L.layerGroup();
BASEMAP.roads.forEach(r=>L.marker([r.lat,r.lon],{pane:'labels',interactive:false,keyboard:false,icon:L.divIcon({className:'street-label',html:`<span style="transform:rotate(${r.angle}deg)">${ESC(r.name)}</span>`,iconSize:[180,15],iconAnchor:[90,7]})}).addTo(streetLabels));
function toggleRoadLabels(){if(map.getZoom()>=14){if(!map.hasLayer(streetLabels))streetLabels.addTo(map)}else map.removeLayer(streetLabels);labels.eachLayer(l=>{const e=l.getElement();if(e)e.style.opacity=map.getZoom()>=15?'.45':'1';});}
map.on('zoomend',toggleRoadLabels);
const markers=L.layerGroup().addTo(map),routeLines=L.layerGroup().addTo(map);
function visibleShops(){const q=state.query.toLowerCase().trim();return shops.filter(s=>(state.category==='all'||s.cat===state.category)&&(state.area==='all'||s.area.startsWith(state.area))&&(!q||JSON.stringify([s.name,s.short,s.area,s.street,s.zh,s.tags,s.selection||[]]).toLowerCase().includes(q)));}
function visibleFactories(){return factories.filter(s=>state.era==='all'||s.era===state.era);}
function mapItems(){let items;if(state.view==='saved')items=saved.map(id=>byId[id]).filter(s=>s.lat!==null);else if(state.route&&state.view==='routes')items=routes.find(r=>r.id===state.route).ids.map(id=>byId[id]);else items=[...(state.layer==='history'?[]:visibleShops()),...(state.layer==='today'?[]:visibleFactories().filter(s=>s.lat!==null))];const selected=byId[state.selected];if(selected&&selected.lat!==null&&!items.some(s=>s.id===selected.id))items.push(selected);return items.filter(s=>Number.isFinite(s.lat)&&Number.isFinite(s.lon));}
function getItems(){if(state.view==='history')return visibleFactories();if(state.view==='saved')return saved.map(id=>byId[id]);if(state.view==='routes'&&state.route)return routes.find(r=>r.id===state.route).ids.map(id=>byId[id]);return visibleShops();}
function renderMarkers(){markers.clearLayers();const pts=mapItems();const groups=[];for(const s of pts){const p=map.latLngToLayerPoint([s.lat,s.lon]);const g=groups.find(g=>p.distanceTo(g.p)<50&&!g.items.some(x=>x.id===state.selected)&&s.id!==state.selected);if(g){g.items.push(s);g.lat+=s.lat;g.lon+=s.lon;g.p=map.latLngToLayerPoint([g.lat/g.items.length,g.lon/g.items.length])}else groups.push({p,items:[s],lat:s.lat,lon:s.lon});}
 let merging=true;while(merging){merging=false;outer:for(let i=0;i<groups.length;i++)for(let j=i+1;j<groups.length;j++){const a=groups[i],b=groups[j];if([...a.items,...b.items].some(s=>s.id===state.selected))continue;if(a.p.distanceTo(b.p)<51){a.items.push(...b.items);a.lat+=b.lat;a.lon+=b.lon;a.p=map.latLngToLayerPoint([a.lat/a.items.length,a.lon/a.items.length]);groups.splice(j,1);merging=true;break outer;}}}
 for(const g of groups){if(g.items.length>1){const n=g.items.length;const m=L.marker([g.lat/n,g.lon/n],{title:`${n} destinations: ${g.items.map(s=>s.short).join(', ')}`,icon:L.divIcon({className:'pin-shell',html:`<span class="cluster">${n}<small>STOPS</small></span>`,iconSize:[43,43],iconAnchor:[21.5,21.5]})}).addTo(markers);m.on('click',()=>{if(map.getZoom()>=15.5){showCluster(g.items);return;}map.fitBounds(g.items.map(s=>[s.lat,s.lon]),{padding:[65,65],maxZoom:16,animate:!reduced});});}
 else {const s=g.items[0],hist=s.type==='factory',color=hist?'#8b6c43':CAT[s.cat].color;const m=L.marker([s.lat,s.lon],{title:`${s.number}. ${s.short} — ${s.area}`,alt:s.short,icon:L.divIcon({className:'pin-shell',html:`<span class="pin ${hist?'history':''} ${state.selected===s.id?'selected':''}" style="--pin:${color}"><span>${String(s.number).padStart(2,'0')}</span></span>`,iconSize:[44,44],iconAnchor:[22,22]}),zIndexOffset:state.selected===s.id?1000:0}).addTo(markers);m.bindTooltip(ESC(s.short),{direction:'top',offset:[0,-17]});m.on('click',()=>select(s.id));}}
}
map.on('zoomend moveend',renderMarkers);
function fitMap(items=mapItems()){map.stop();const p=items.filter(s=>s.lat!==null&&s.lat!==undefined).map(s=>[s.lat,s.lon]);if(!p.length)return;if(p.length===1)map.setView(p[0],14,{animate:!reduced});else map.fitBounds(p,{padding:innerWidth<=760?[25,65]:[55,70],maxZoom:14,animate:!reduced});}
function drawRoute(){routeLines.clearLayers();let ids=[];if(state.route&&state.view==='routes')ids=routes.find(r=>r.id===state.route).ids;if(state.view==='saved')ids=saved;const p=ids.map(id=>byId[id]).filter(s=>s.lat!==null).map(s=>[s.lat,s.lon]);if(p.length>1)L.polyline(p,{color:'#743c40',weight:2,opacity:.6,dashArray:'5 9',interactive:false}).addTo(routeLines);$('map-note').innerHTML=p.length>1?'Dashed line = visit sequence.<br>Use a navigation app for the journey.':state.layer==='today'?'Address-checked pins.<br>Open a card for the building, unit and pin precision.':'Factory sites on today’s streets.<br>Historical locations ≠ tour availability.';}
function syncLayers(){document.querySelectorAll('[data-layer]').forEach(b=>{b.classList.toggle('active',b.dataset.layer===state.layer);b.setAttribute('aria-pressed',String(b.dataset.layer===state.layer));});drawRoute();renderMarkers();if(!mapItems().length)$('map-note').innerHTML=state.view==='history'?'This record has no verified map location yet.':'No mapped stops match this selection.';$('nudge').hidden=state.view!=='shops'||!!state.selected||state.layer!=='today';$('map-status').textContent=state.view==='history'?'3 historical sites · 1 contemporary workshop record':state.view==='saved'?`${saved.length} saved destinations · your order`:state.route?'An editorial sequence, not turn-by-turn directions':`${visibleShops().length} of 21 destinations · made for exploring`;}
const orderedShops=()=>{const priority=['ro','eth','cw','lm','md'];return [...visibleShops()].sort((a,b)=>{let i=priority.indexOf(a.id),j=priority.indexOf(b.id);return(i<0?99:i)-(j<0?99:j)||a.number-b.number;});};
function row(s,trip=false){const hist=s.type==='factory',inSaved=saved.includes(s.id);return `<article class="stop-row ${hist?'history-row':''} ${state.selected===s.id?'selected':''}" data-row="${s.id}"><div class="row-top"><span class="index-no">${String(s.number).padStart(2,'0')}</span><span>${ESC(s.area)}</span></div><button class="row-save ${inSaved?'saved':''}" data-save="${s.id}" aria-label="${inSaved?'Remove':'Save'} ${ESC(s.short)}" aria-pressed="${inSaved}">${icon('bookmark')}</button><button class="row-main" data-select="${s.id}"><h3>${ESC(s.short)}</h3><p>${ESC(s.strap)}</p></button>${hist?`<span class="status-badge">${ESC(s.status)}</span><p class="coordinate">${s.lat===null?'Address / map location awaiting confirmation':ESC(s.period)}</p>`:`<div class="row-meta"><span class="dot" style="background:${CAT[s.cat].color}"></span><span>${CAT[s.cat].name}</span>${s.warning?'<span class="check-tag"> · Check ahead</span>':''}</div>`}${trip?`<div class="saved-row-controls"><button data-move="${s.id}:-1" ${saved.indexOf(s.id)===0?'disabled':''} aria-label="Move ${ESC(s.short)} earlier">↑ Earlier</button><button data-move="${s.id}:1" ${saved.indexOf(s.id)===saved.length-1?'disabled':''} aria-label="Move ${ESC(s.short)} later">↓ Later</button><button data-save="${s.id}">Remove</button></div>`:''}</article>`;}
function renderShopHead(){const areas=['Jing’an','Xuhui','Xujiahui','Huangpu','Pudong','Changning','Putuo','Hongkou'];$('sidebar-head').innerHTML=`<div class="sidebar-top"><h2>Find your next pair.</h2><p>Twenty-two addresses, chosen for the shoes.</p><label class="search">${icon('search')}<input id="search" aria-label="Search shops, makers or addresses" placeholder="Alden, GUIDI, Feiyue…" value="${ESC(state.query)}"><button id="clear-search" aria-label="Clear search">${icon('close')}</button></label><div class="filters" aria-label="Filter by category"><button class="pill ${state.category==='all'?'active':''}" data-category="all">All</button>${Object.entries(CAT).map(([k,v])=>`<button class="pill ${state.category===k?'active':''}" data-category="${k}"><span class="dot" style="background:${v.color}"></span>${v.short}</button>`).join('')}</div></div><div class="results-heading"><span id="result-count"></span><select id="area-filter" aria-label="Filter by neighbourhood"><option value="all">All neighbourhoods</option>${areas.map(a=>`<option ${state.area===a?'selected':''}>${a}</option>`).join('')}</select></div>`;
 $('search').addEventListener('input',e=>{state.query=e.target.value;renderShopRows();closeDetail(false);syncLayers();});$('area-filter').addEventListener('change',e=>{state.area=e.target.value;renderShopRows();closeDetail(false);syncLayers();fitMap();});$('clear-search').onclick=()=>{state.query='';$('search').value='';renderShopRows();syncLayers();$('search').focus();};}
function renderShopRows(){const list=orderedShops();$('result-count').textContent=`${list.length} OF 21 STOPS`;$('results').innerHTML=list.length?list.map(s=>row(s)).join(''):`<div class="empty"><h3>A different direction?</h3><p>No stops match those filters. Try another maker or clear the filters.</p><button class="button" data-reset>Show all 21 stops</button></div>`;updateMobile();}
function renderSidebar(){if(state.view==='shops'){renderShopHead();renderShopRows();}
 if(state.view==='routes'){$('sidebar-head').innerHTML='<div class="section-intro"><span class="smallcaps muted">Make an afternoon of it</span><h2>Three ways into the city.</h2><p>Choose a few stops. Leave room for fitting, conversation and the streets in between.</p></div>';$('results').innerHTML=routes.map(r=>`<article class="route-row ${state.route===r.id?'active':''}"><span class="route-number">${r.n}</span><div class="smallcaps muted" style="margin-top:4px;font-size:8px">${r.area}</div><h3>${r.name}</h3><p>${r.description}</p><div class="route-hint">${r.ids.length} core stops · ${r.time}</div>${state.route===r.id?`${r.ids.map((id,i)=>`<button class="route-stop" data-select="${id}"><span>${i+1}.</span>${byId[id].short} ${icon('arrow')}</button>`).join('')}<p style="margin-top:14px">${r.note}</p><div class="route-actions"><button class="button primary" data-save-route="${r.id}">${icon('bookmark')} Save route</button><button class="button" data-route="${r.id}">${icon('expand')} Fit map</button></div><details class="source-details"><summary>Optional nearby & extended stops</summary>${r.optional.map(id=>`<button class="route-stop" data-select="${id}">${byId[id].short} · ${byId[id].area}</button>`).join('')}</details>`:`<button class="button" data-route="${r.id}">Explore this route ${icon('arrow')}</button>`}</article>`).join('');}
 if(state.view==='history'){$('sidebar-head').innerHTML=`<div class="section-intro history-intro"><span class="smallcaps">The city beneath the shoes</span><h2>Made in Shanghai.</h2><p>Old factories. New uses. Continuing craft.<br>A growing archive on the city’s present-day map.</p><div class="filters"><button class="pill ${state.era==='all'?'active':''}" data-era="all">All records</button><button class="pill ${state.era==='origins'?'active':''}" data-era="origins">Origins</button><button class="pill ${state.era==='afterlives'?'active':''}" data-era="afterlives">Afterlives</button><button class="pill ${state.era==='active'?'active':''}" data-era="active">Making today</button></div></div><div class="results-heading"><span>${visibleFactories().length} RECORDS · ${visibleFactories().filter(s=>s.lat!==null).length} MAPPED</span><span>Research edition</span></div>`;$('results').innerHTML=visibleFactories().map(s=>row(s)).join('')+`<section class="future"><span class="smallcaps muted">The next chapter</span><h3>Inside the workshop.</h3><p>Factory and atelier visits are a future part of the circuit. Feiyue and Oct Tenth are among the possibilities being explored.</p><button class="text-button" data-modal="tours">About future visits →</button></section>`;}
 if(state.view==='saved'){$('sidebar-head').innerHTML=`<div class="section-intro"><span class="smallcaps muted">Your Shanghai afternoon</span><h2>My circuit<span style="color:var(--red)">.</span></h2><p>${saved.length?`${saved.length} saved stops. Arrange them in the order you’d like to visit. Lines connect the sequence; they are not walking directions.`:'Keep a short list of the places you want to visit. Tap a bookmark on any destination to begin.'}</p>${saved.length?`<div class="saved-tools"><button class="button primary" id="download-trip">${icon('download')} Save addresses</button><button class="button" id="print-trip">Print</button></div>`:''}<p class="coordinate">${storageOK?'Saved on this device.':'This browser cannot retain saves; download your address list.'}</p></div>`;$('results').innerHTML=saved.length?saved.map(id=>row(byId[id],true)).join(''):'<div class="empty"><h3>A day, well spent.</h3><p>Start with Roiluxe for classic shoemaking, eth0s for the avant-garde, or a route through the city.</p><button class="button" data-view="shops">Explore the shops →</button></div>';if(saved.length){$('download-trip').onclick=downloadTrip;$('print-trip').onclick=printTrip;}}
 updateMobile();icons($('sidebar-head'));
}
function setView(view){state.view=view;state.route=view==='routes'?state.route:null;if(view==='history')state.layer='history';if(view==='shops'||view==='routes')state.layer='today';state.list=matchMedia('(max-width:760px)').matches;closeDetail(false);document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});renderSidebar();syncLayers();map.invalidateSize();fitMap();}
function setLayer(layer){state.layer=layer;if(layer==='history'){state.view='history';state.era='all';}else if(layer==='today'){state.view='shops';}else if(state.view==='saved'||state.view==='routes'){state.view='shops';}state.route=null;closeDetail(false);document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('active',b.dataset.view===state.view);if(b.dataset.view===state.view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});renderSidebar();syncLayers();fitMap();}
function updateMobile(){$('app').classList.toggle('list-mode',state.list);$('mobile-toggle').innerHTML=icon(state.list?'map':'list')+`<span>${state.list?'Show map':state.view==='shops'?`Browse ${visibleShops().length} stops`:state.view==='history'?'Browse factory history':state.view==='routes'?'Browse routes':'Open my circuit'}</span>`;}
function toggleSave(id){const was=saved.includes(id);saved=was?saved.filter(x=>x!==id):[...saved,id];persist();renderSidebar();if(state.selected)renderDetail(byId[state.selected]);syncLayers();toast(was?'Removed from your circuit':storageOK?'Saved to your circuit':'Saved for this visit. Download your address list to keep it.');}
function sourceHTML(s){const list=s.sources||[];return`<details class="source-details"><summary>Sources & field notes</summary><p>${ESC(s.evidence||'Dates describe documented events. Present access and operating status may have changed.')}</p><p>${ESC(s.coordNote||'See the address and location note for this destination.')}</p>${s.type==='shop'?'<p>Selection records describe reported offerings, not live stock. Confirm your size, the branch and opening hours before a special journey.</p>':''}<ul>${list.length?list.map(l=>`<li><a href="${ESC(l.url)}" target="_blank" rel="noopener">${ESC(l.label)} ↗</a></li>`).join(''):'<li>Source: the July 2026 Shanghai Shoe Circuit guide.</li>'}</ul><p>${s.locationChecked?'Address and map position reviewed '+ESC(s.locationChecked)+'.':'Guide edited 7 October 2026.'}</p></details>`;}
function renderDetail(s){const hist=s.type==='factory',inSaved=saved.includes(s.id);$('detail-caption').textContent=hist?'Factory archive / '+s.number:'Destination '+String(s.number).padStart(2,'0')+' / 21';const q=encodeURIComponent('上海 '+s.zh);const canTravel=!hist||(s.lat!==null);$('detail-content').innerHTML=`<div class="eyebrow">${hist?icon('factory'):`<span class="dot" style="background:${CAT[s.cat].color}"></span>`}${hist?ESC(s.status):CAT[s.cat].name}</div><h2>${ESC(s.short)}</h2><p class="strap">${ESC(s.area)}<br>${ESC(s.strap)}</p><p class="description">${ESC(s.description)}</p>${s.warning?`<div class="warning">${ESC(s.warning)}</div>`:''}${hist?`<div class="timeline">${s.timeline.map(([year,t])=>`<div><b>${year}</b><p>${ESC(t)}</p></div>`).join('')}</div><div class="detail-section"><h4>What is there now?</h4><p class="description">${ESC(s.now)}</p></div><div class="warning">${ESC(s.visit)}</div>`:`<div class="detail-section"><h4>Look for · recorded selection</h4><div class="brands">${s.tags.map(t=>`<span>${ESC(t)}</span>`).join('')}</div>${s.selection?`<details class="source-details" style="margin-top:13px;border:0;padding:0"><summary>More about the recorded footwear</summary><div class="selection-notes">${s.selection.map(([l,v])=>`<p><b>${ESC(l)}</b><br>${ESC(v)}</p>`).join('')}</div></details>`:''}</div>`}<div class="detail-section"><h4>${hist?'Site address':'Plan your visit'}</h4><p class="address">${ESC(s.street)}</p><p class="address-zh" lang="zh-CN">${ESC(s.zh)}</p>${s.hours?`<div class="hours">${icon('clock')}<span>${ESC(s.hours)}</span></div>`:''}${s.phone?`<a class="phone" href="tel:${s.phone.replace(/[^+\d]/g,'')}">${ESC(s.phone)}</a>`:''}<div class="detail-actions"><button class="button primary" data-save="${s.id}">${icon(inSaved?'check':'bookmark')}${inSaved?'Saved':'Save stop'}</button><button class="button" data-taxi="${s.id}">${icon('taxi')}${hist?'Address card':'Taxi card'}</button></div>${canTravel?`<div class="directions"><a href="https://uri.amap.com/search?keyword=${q}&city=上海&src=StudyInShell&callnative=0" target="_blank" rel="noopener">Search in Amap ↗</a><a href="https://maps.apple.com/?q=${q}" target="_blank" rel="noopener">Apple Maps ↗</a></div>`:''}<p class="coordinate">${s.lat===null?'Not plotted: map location awaiting confirmation.':hist?'Approximate site anchor, not a factory footprint.':ESC(s.pinLabel||'Address pin · check the entrance')}</p></div>${sourceHTML(s)}`;const list=getItems();let i=list.findIndex(x=>x.id===s.id);$('detail-position').textContent=i<0?'Field notes':`${i+1} / ${list.length}`;}
function select(id){const s=byId[id];if(!s)return;map.stop();state.selected=id;$('detail').classList.add('open');$('detail').setAttribute('aria-hidden','false');$('detail').inert=false;renderDetail(s);$('detail-content').scrollTop=0;renderMarkers();document.querySelectorAll('[data-row]').forEach(e=>e.classList.toggle('selected',e.dataset.row===id));$('nudge').hidden=true;if(s.lat!==null){if(state.list&&matchMedia('(max-width:760px)').matches){state.list=false;updateMobile();map.invalidateSize();}const zoom=Math.max(14,map.getZoom());if(innerWidth>760){const desired=L.point((map.getSize().x-360)/2,map.getSize().y/2);const loc=map.project([s.lat,s.lon],zoom);const center=loc.subtract(desired).add(map.getSize().divideBy(2));map.setView(map.unproject(center,zoom),zoom,{animate:!reduced});}else map.setView([s.lat,s.lon],zoom,{animate:!reduced});}if(innerWidth<=760)$('close-detail').focus({preventScroll:true});}
function closeDetail(focus=true){state.selected=null;$('detail').classList.remove('open');$('detail').setAttribute('aria-hidden','true');$('detail').inert=true;document.querySelectorAll('[data-row]').forEach(e=>e.classList.remove('selected'));if(focus)$('map').focus({preventScroll:true});renderMarkers();$('nudge').hidden=state.view!=='shops'||state.layer!=='today';}
$('detail').inert=true;$('close-detail').onclick=()=>closeDetail();
function nextStop(d){const list=getItems();if(!list.length)return;const i=list.findIndex(x=>x.id===state.selected);select(list[(i+d+list.length)%list.length].id);}$('previous-stop').onclick=()=>nextStop(-1);$('next-stop').onclick=()=>nextStop(1);
$('fit-map').onclick=()=>{closeDetail(false);fitMap();};$('mobile-toggle').onclick=()=>{state.list=!state.list;updateMobile();map.invalidateSize();};
let toastTimer;function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2700);}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Chinese address copied');}catch{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';$('modal').open?$('modal').append(ta):document.body.append(ta);ta.select();const ok=document.execCommand('copy');ta.remove();toast(ok?'Chinese address copied':'Select and copy the address shown on the card.');}}
let modalOpener;function modal(html){modalOpener=document.activeElement;$('modal-body').innerHTML=html;$('modal').showModal();}function closeModal(){$('modal').close();modalOpener?.focus?.({preventScroll:true});}$('close-modal').onclick=closeModal;$('modal').addEventListener('click',e=>{if(e.target===$('modal')){const r=$('modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
function taxi(id){const s=byId[id];modal(`<p class="smallcaps">${s.type==='factory'?'Historical site / address reference':'Show your driver / 给司机看'}</p><h2>${ESC(s.short)}</h2>${s.type==='shop'?'<p class="taxi-phrase" lang="zh-CN">您好，请带我到这个地址，谢谢。</p>':''}<p class="taxi-zh" lang="zh-CN">${ESC(s.zh)}</p><p>${ESC(s.street)}</p>${s.warning?`<div class="warning">${ESC(s.warning)}</div>`:''}${s.type==='factory'?`<div class="warning">${ESC(s.visit)}</div>`:''}${s.phone?`<p>${ESC(s.phone)}</p>`:''}<button class="button primary wide" data-copy="${id}">${icon('copy')} Copy Chinese address</button><p class="coordinate">${s.type==='shop'?'Check the branch and hours before travelling.':'This is a historical address reference, not a tour reservation.'}</p>`);}
const MODALS={
visiting:`<p class="smallcaps">For a short stay, or a familiar city</p><h2>A few things before you go.</h2><h3>Start with a small circuit.</h3><p>Pick two or three destinations around your hotel or meetings. Special orders, fitting and conversation can make a single stop the best part of an afternoon.</p><h3>Carry the Chinese address.</h3><p>Open a shop’s taxi card and show it to your driver or hotel concierge. “Lu” means road. Building, floor and room numbers matter: some of the most interesting shops are upstairs or inside a lane.</p><h3>Ask ahead.</h3><p>Check the branch, hours and your size before a special journey. For appointments or repairs, send photographs and measurements first. English-language assistance is not confirmed for every stop.</p><h3>Keep your day with you.</h3><p>Bookmark stops in My circuit, put them in order and save the address list. The guide and its map work offline once this file is downloaded; external links and navigation services need a connection.</p><h3>History is a different kind of visit.</h3><p>A former factory may now be housing, offices or a cultural venue. Read each site’s access note. A historical pin never implies an invitation to enter.</p>`,
tours:`<p class="smallcaps">A future Study in Shell chapter</p><h2>Inside the workshop.</h2><p>The next step is to connect the city’s shops with the people and places that make its shoes. Feiyue and Oct Tenth are among the possibilities for future factory and atelier visits.</p><h3>What a visit could offer</h3><p>Materials on the bench. Lasts and cutting. The difference between assembly and handwork. A conversation with the people doing it.</p><div class="warning">No tours are currently offered or bookable through this guide. Sites, hosts, dates, language support and visitor access must be agreed before a visit is listed.</div><p>The factory archive is already open for exploration. It distinguishes documented historical sites from contemporary production records and makes missing information visible.</p><button class="button" id="go-history">Explore the factory archive →</button>`,
about:`<p class="smallcaps">Study in Shell / Shanghai field guide</p><h2>For people who notice shoes.</h2><p>A city guide to shoemaking, considered retail and the industrial history behind the footwear. Built from the July 2026 Shoe Circuit and its October additions; redesigned and edited on 7 October 2026.</p><h3>What the map means</h3><p>Twenty-two shops and services sit alongside a separate factory archive. Numbered circles are shopping destinations; diamonds identify approximate historical-site anchors. Clusters expand as you zoom. Dashed lines show visit order, not navigable routes.</p><p>The street map is a modern OpenStreetMap base, not a reconstruction of historical streets. Shop locations were re-researched on 7 October 2026 and aligned to this map’s coordinate system. Each card distinguishes a mapped shop from a building or street-address pin. Historical-site anchors are labelled individually; a record without a resolved location is listed without a pin.</p><h3>Sources and confidence</h3><p>Each card keeps its own source links and field notes. Shop selection is recorded, not live inventory. The Real Real Co.’s occupancy and Radiance Blue’s indoor unit still need confirmation. Hours and access should be checked before a special journey. Historical dates refer to documented events, not continuous operation or current public access.</p><h3>Your circuit</h3><p>Bookmarks are saved in your browser on this device, when storage is available. They are not sent to a server or synced between devices. Download the address list to keep a portable copy.</p><h3>Map credits</h3><p>Map data © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap contributors</a>; vector data via <a href="https://openfreemap.org" target="_blank" rel="noopener">OpenFreeMap</a> and © <a href="https://openmaptiles.org" target="_blank" rel="noopener">OpenMapTiles</a>. The embedded regional data snapshot is dated 27 September 2026. Map interaction by <a href="https://leafletjs.com" target="_blank" rel="noopener">Leaflet</a>. Map assets and fonts are embedded in this file.</p>`};
function showCluster(items){modal(`<p class="smallcaps">Close together on the map</p><h2>${items.length} places to explore.</h2>${items.map(s=>`<button class="route-stop" data-cluster-select="${s.id}">${s.short} · ${s.area} ${icon('arrow')}</button>`).join('')}`);}
function tripText(){return 'STUDY IN SHELL — MY SHANGHAI CIRCUIT\nPrepared from the October 2026 guide\nCheck addresses, hours and appointments before visiting.\n\n'+saved.map((id,i)=>{const s=byId[id];return`${i+1}. ${s.short} — ${s.area}\n${s.street}\n${s.zh}\n${s.hours||s.visit}${s.phone?'\n'+s.phone:''}${s.warning?'\nCHECK: '+s.warning:''}`}).join('\n\n');}
function downloadTrip(){const b=new Blob([tripText()],{type:'text/plain;charset=utf-8'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='Study-in-Shell-My-Shanghai-Circuit.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);toast('Address list downloaded');}
function printTrip(){$('print-sheet').innerHTML=`<p>STUDY IN SHELL / SHANGHAI</p><h1>My Shanghai circuit</h1><p>October 2026 · Check addresses, hours and appointments before visiting.</p>${saved.map((id,i)=>{const s=byId[id];return`<section><h2>${i+1}. ${ESC(s.short)}</h2><p>${ESC(s.area)} · ${ESC(s.street)}</p><p class="zh">${ESC(s.zh)}</p><p>${ESC(s.hours||s.visit)}</p>${s.phone?`<p>${ESC(s.phone)}</p>`:''}${s.warning?`<p>Check: ${ESC(s.warning)}</p>`:''}</section>`}).join('')}`;window.print();}
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.view){setView(t.dataset.view);return;}if(t.dataset.layer){setLayer(t.dataset.layer);return;}if(t.dataset.category){state.category=t.dataset.category;closeDetail(false);renderSidebar();syncLayers();fitMap();return;}if(t.dataset.era){state.era=t.dataset.era;closeDetail(false);renderSidebar();syncLayers();fitMap();return;}if(t.dataset.select){select(t.dataset.select);return;}if(t.dataset.save){toggleSave(t.dataset.save);return;}if(t.dataset.route){state.route=t.dataset.route;state.layer='today';closeDetail(false);renderSidebar();syncLayers();if(innerWidth<=760){state.list=false;updateMobile();map.invalidateSize();}fitMap();return;}if(t.dataset.saveRoute){const r=routes.find(x=>x.id===t.dataset.saveRoute);saved=[...new Set([...saved,...r.ids])];persist();toast(`${r.ids.length} route stops added to your circuit`);return;}if(t.dataset.move){const[id,dir]=t.dataset.move.split(':');const i=saved.indexOf(id),j=i+Number(dir);if(j>=0&&j<saved.length){[saved[i],saved[j]]=[saved[j],saved[i]];persist();renderSidebar();drawRoute();}return;}if(t.dataset.taxi){taxi(t.dataset.taxi);return;}if(t.dataset.copy){copy(byId[t.dataset.copy].zh);return;}if(t.dataset.modal){modal(MODALS[t.dataset.modal]);return;}if(t.dataset.clusterSelect){closeModal();select(t.dataset.clusterSelect);return;}if(t.hasAttribute('data-reset')){state.query='';state.category='all';state.area='all';renderSidebar();syncLayers();fitMap();return;}if(t.id==='go-history'){closeModal();setView('history');}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('modal').open)closeDetail(false);if(e.target.closest('input,select,textarea,dialog'))return;if(state.selected&&e.target.closest('#detail')){if(e.key==='ArrowRight')nextStop(1);if(e.key==='ArrowLeft')nextStop(-1);}});
window.addEventListener('resize',()=>{map.invalidateSize();renderMarkers();});
renderSidebar();syncLayers();setTimeout(()=>{map.invalidateSize();fitMap(shops);},100);
// A stable data model separates retail stops, historical places and future visitor access.
// No fabricated shop stock, appointment bookings, tour inventory or live-open status.
window.SIS={map,get state(){return {...state}},get saved(){return [...saved]},shops,factories,routes,mapItems,select,setView};
